// src/lib/templates.ts — Pre-built real-world system architecture templates.
import type { FlowNode, FlowEdge } from "@/types/canvas";

export interface ArchitectureTemplate {
  id: string;
  name: string;
  badge: string;
  description: string;
  nodeCount: number;
  nodes: FlowNode[];
  edges: FlowEdge[];
}

export const ARCHITECTURE_TEMPLATES: ArchitectureTemplate[] = [
  {
    id: "ecommerce",
    name: "E-Commerce Microservices",
    badge: "Enterprise",
    description: "Production microservices with Kong, Kafka, Postgres, and Redis cache",
    nodeCount: 8,
    nodes: [
      {
        id: "client-web",
        type: "client",
        position: { x: 380, y: 40 },
        data: {
          id: "client-web",
          type: "client",
          name: "Storefront Web App",
          technology: "Next.js / TypeScript",
          description: "High-performance customer storefront and checkout interface",
          responsibilities: ["SSR Rendering", "Cart UI", "Stripe Checkout SDK"],
        },
      },
      {
        id: "gateway-kong",
        type: "gateway",
        position: { x: 380, y: 160 },
        data: {
          id: "gateway-kong",
          type: "gateway",
          name: "Kong API Gateway",
          technology: "Kong / Envoy",
          description: "Central ingress router with rate limiting and TLS termination",
          responsibilities: ["Rate Limiting", "TLS Termination", "Auth Token Verification"],
        },
      },
      {
        id: "service-auth",
        type: "service",
        position: { x: 140, y: 280 },
        data: {
          id: "service-auth",
          type: "service",
          name: "Auth & Identity Service",
          technology: "Go / Gin",
          description: "JWT token issuing, OAuth providers, and user credentials",
          responsibilities: ["User Auth", "JWT Issuance", "Session Verification"],
        },
      },
      {
        id: "service-order",
        type: "service",
        position: { x: 380, y: 280 },
        data: {
          id: "service-order",
          type: "service",
          name: "Order Processing Service",
          technology: "Node.js / Express",
          description: "Cart orchestration, order validation, and checkout state",
          responsibilities: ["Cart Validation", "Order Creation", "Publish Events"],
        },
      },
      {
        id: "cache-redis",
        type: "cache",
        position: { x: 620, y: 280 },
        data: {
          id: "cache-redis",
          type: "cache",
          name: "Redis Session Cache",
          technology: "Redis 7.2",
          description: "Ephemeral user shopping carts and active sessions",
          responsibilities: ["Cart Storage", "Token Blacklist", "Fast Lookup"],
        },
      },
      {
        id: "queue-kafka",
        type: "queue",
        position: { x: 380, y: 400 },
        data: {
          id: "queue-kafka",
          type: "queue",
          name: "Kafka Order Stream",
          technology: "Apache Kafka",
          description: "Decoupled distributed message broker for domain events",
          responsibilities: ["OrderPlaced Event", "PaymentInitiated Event", "Audit Stream"],
        },
      },
      {
        id: "service-fulfillment",
        type: "service",
        position: { x: 140, y: 520 },
        data: {
          id: "service-fulfillment",
          type: "service",
          name: "Fulfillment & Inventory",
          technology: "Rust / Actix",
          description: "Stock reservations and shipping dispatch worker",
          responsibilities: ["Stock Locking", "Warehouse Routing", "Tracking Info"],
        },
      },
      {
        id: "db-postgres",
        type: "database",
        position: { x: 620, y: 520 },
        data: {
          id: "db-postgres",
          type: "database",
          name: "Orders PostgreSQL",
          technology: "PostgreSQL 16",
          description: "ACID compliant transactional ledger for orders and payments",
          responsibilities: ["Order Storage", "Payment Ledger", "Audit Trails"],
        },
      },
    ],
    edges: [
      {
        id: "e-client-gw",
        source: "client-web",
        target: "gateway-kong",
        type: "semantic",
        data: { relationship: "connects_to", label: "HTTPS / TLS", protocol: "HTTP/2" },
      },
      {
        id: "e-gw-auth",
        source: "gateway-kong",
        target: "service-auth",
        type: "semantic",
        data: { relationship: "connects_to", label: "verify tokens", protocol: "gRPC" },
      },
      {
        id: "e-gw-order",
        source: "gateway-kong",
        target: "service-order",
        type: "semantic",
        data: { relationship: "connects_to", label: "checkout requests", protocol: "HTTP/REST" },
      },
      {
        id: "e-order-cache",
        source: "service-order",
        target: "cache-redis",
        type: "semantic",
        data: { relationship: "reads_from", label: "session cart data", protocol: "TCP/RESP" },
      },
      {
        id: "e-order-kafka",
        source: "service-order",
        target: "queue-kafka",
        type: "semantic",
        data: { relationship: "publishes_to", label: "OrderCreated event", protocol: "TCP/Kafka" },
      },
      {
        id: "e-kafka-fulfillment",
        source: "queue-kafka",
        target: "service-fulfillment",
        type: "semantic",
        data: { relationship: "subscribes_to", label: "consume order stream", protocol: "TCP/Kafka" },
      },
      {
        id: "e-order-db",
        source: "service-order",
        target: "db-postgres",
        type: "semantic",
        data: { relationship: "writes_to", label: "commit order", protocol: "PostgreSQL Wire" },
      },
    ],
  },
  {
    id: "rag-ai",
    name: "Enterprise AI RAG Pipeline",
    badge: "AI / ML",
    description: "Vector search, LLM inference router, Redis semantic cache, and Postgres",
    nodeCount: 7,
    nodes: [
      {
        id: "rag-client",
        type: "client",
        position: { x: 380, y: 40 },
        data: {
          id: "rag-client",
          type: "client",
          name: "Copilot Web UI",
          technology: "React / Vite",
          description: "Interactive chat assistant frontend for knowledge querying",
          responsibilities: ["Markdown Render", "Streaming UI", "Citation Badges"],
        },
      },
      {
        id: "rag-gateway",
        type: "gateway",
        position: { x: 380, y: 160 },
        data: {
          id: "rag-gateway",
          type: "gateway",
          name: "FastAPI Ingress Router",
          technology: "FastAPI / Uvicorn",
          description: "Validates queries and dispatches to semantic cache or embedding pipeline",
          responsibilities: ["Prompt Sanitization", "Auth Verification", "SSE Streaming"],
        },
      },
      {
        id: "rag-cache",
        type: "cache",
        position: { x: 620, y: 280 },
        data: {
          id: "rag-cache",
          type: "cache",
          name: "Semantic Vector Cache",
          technology: "Redis Vector 7",
          description: "Caches cosine similarity embeddings of frequent questions",
          responsibilities: ["Similarity Matching", "Zero-Latency Hit", "TTL Purge"],
        },
      },
      {
        id: "rag-service-embed",
        type: "service",
        position: { x: 140, y: 280 },
        data: {
          id: "rag-service-embed",
          type: "service",
          name: "Embedding & Chunking",
          technology: "Python / PyTorch",
          description: "Generates high-dimensional vector embeddings for user questions",
          responsibilities: ["Token Chunking", "Text-embedding-3-small", "Normalization"],
        },
      },
      {
        id: "rag-vectordb",
        type: "database",
        position: { x: 140, y: 420 },
        data: {
          id: "rag-vectordb",
          type: "database",
          name: "Qdrant Vector DB",
          technology: "Qdrant / HNSW",
          description: "Stores document embeddings and executes cosine similarity searches",
          responsibilities: ["HNSW Index", "Filtered KNN Search", "Payload Metadata"],
        },
      },
      {
        id: "rag-service-llm",
        type: "service",
        position: { x: 380, y: 420 },
        data: {
          id: "rag-service-llm",
          type: "service",
          name: "Inference & Synthesis",
          technology: "LangChain / OpenAI",
          description: "Augments prompt with retrieved contexts and streams final answer",
          responsibilities: ["Context Synthesis", "Guardrails Check", "Streaming Tokens"],
        },
      },
      {
        id: "rag-db-meta",
        type: "database",
        position: { x: 620, y: 420 },
        data: {
          id: "rag-db-meta",
          type: "database",
          name: "Document Metadata DB",
          technology: "PostgreSQL 16",
          description: "Stores original document texts, user access logs, and ratings",
          responsibilities: ["Document Raw Text", "Permissions", "Audit Analytics"],
        },
      },
    ],
    edges: [
      {
        id: "e-rag-1",
        source: "rag-client",
        target: "rag-gateway",
        type: "semantic",
        data: { relationship: "connects_to", label: "stream prompt", protocol: "HTTPS / SSE" },
      },
      {
        id: "e-rag-2",
        source: "rag-gateway",
        target: "rag-cache",
        type: "semantic",
        data: { relationship: "reads_from", label: "check semantic hit", protocol: "RESP" },
      },
      {
        id: "e-rag-3",
        source: "rag-gateway",
        target: "rag-service-embed",
        type: "semantic",
        data: { relationship: "connects_to", label: "embed text", protocol: "gRPC" },
      },
      {
        id: "e-rag-4",
        source: "rag-service-embed",
        target: "rag-vectordb",
        type: "semantic",
        data: { relationship: "reads_from", label: "KNN vector search", protocol: "gRPC" },
      },
      {
        id: "e-rag-5",
        source: "rag-vectordb",
        target: "rag-service-llm",
        type: "semantic",
        data: { relationship: "connects_to", label: "inject top-K chunks", protocol: "Internal" },
      },
      {
        id: "e-rag-6",
        source: "rag-service-llm",
        target: "rag-db-meta",
        type: "semantic",
        data: { relationship: "writes_to", label: "log conversation trace", protocol: "Postgres" },
      },
    ],
  },
  {
    id: "realtime-chat",
    name: "Realtime WebSocket Engine",
    badge: "Distributed",
    description: "High-concurrency chat with WebSocket Gateway, Redis PubSub, and ScyllaDB",
    nodeCount: 6,
    nodes: [
      {
        id: "chat-client",
        type: "client",
        position: { x: 380, y: 40 },
        data: {
          id: "chat-client",
          type: "client",
          name: "Chat Desktop / Web",
          technology: "Tauri / React",
          description: "Sub-50ms latency messaging UI with presence indicators",
          responsibilities: ["WebSocket Heartbeat", "Message Rendering", "Typing Indicator"],
        },
      },
      {
        id: "chat-gateway",
        type: "gateway",
        position: { x: 380, y: 160 },
        data: {
          id: "chat-gateway",
          type: "gateway",
          name: "WebSocket Ingress Gateway",
          technology: "Envoy Proxy",
          description: "Connection pooling and stickiness for WebSocket sessions",
          responsibilities: ["WSS Upgrade", "Connection Keepalive", "Session Pinning"],
        },
      },
      {
        id: "chat-service-presence",
        type: "service",
        position: { x: 180, y: 280 },
        data: {
          id: "chat-service-presence",
          type: "service",
          name: "Presence & Session Service",
          technology: "Go / Gorilla WS",
          description: "Maintains live connected socket state and heartbeats",
          responsibilities: ["Online Tracking", "Heartbeat Ping", "Channel Join/Leave"],
        },
      },
      {
        id: "chat-pubsub",
        type: "cache",
        position: { x: 580, y: 280 },
        data: {
          id: "chat-pubsub",
          type: "cache",
          name: "Redis Pub/Sub Cluster",
          technology: "Redis Cluster 7",
          description: "Ultra-fast broadcast channel across multi-node socket workers",
          responsibilities: ["Channel Fanout", "Presence Broadcast", "Typing Events"],
        },
      },
      {
        id: "chat-queue-persist",
        type: "queue",
        position: { x: 180, y: 420 },
        data: {
          id: "chat-queue-persist",
          type: "queue",
          name: "Message Ingestion Queue",
          technology: "RabbitMQ / NATS",
          description: "Buffers write spikes so storage engine never gets overwhelmed",
          responsibilities: ["Backpressure Buffer", "Guaranteed Delivery", "Dead Letter"],
        },
      },
      {
        id: "chat-db-store",
        type: "database",
        position: { x: 380, y: 420 },
        data: {
          id: "chat-db-store",
          type: "database",
          name: "ScyllaDB Message Archive",
          technology: "ScyllaDB (CQL)",
          description: "Wide-column distributed store optimized for time-series chat logs",
          responsibilities: ["Message History", "Channel Partitions", "Sub-10ms Reads"],
        },
      },
    ],
    edges: [
      {
        id: "e-chat-1",
        source: "chat-client",
        target: "chat-gateway",
        type: "semantic",
        data: { relationship: "connects_to", label: "wss:// duplex channel", protocol: "WebSocket" },
      },
      {
        id: "e-chat-2",
        source: "chat-gateway",
        target: "chat-service-presence",
        type: "semantic",
        data: { relationship: "connects_to", label: "route socket frames", protocol: "gRPC" },
      },
      {
        id: "e-chat-3",
        source: "chat-service-presence",
        target: "chat-pubsub",
        type: "semantic",
        data: { relationship: "publishes_to", label: "broadcast room msg", protocol: "Redis PubSub" },
      },
      {
        id: "e-chat-4",
        source: "chat-service-presence",
        target: "chat-queue-persist",
        type: "semantic",
        data: { relationship: "publishes_to", label: "enqueue async persist", protocol: "AMQP" },
      },
      {
        id: "e-chat-5",
        source: "chat-queue-persist",
        target: "chat-db-store",
        type: "semantic",
        data: { relationship: "writes_to", label: "batch write history", protocol: "CQL Binary" },
      },
    ],
  },
];
