// src/engine/mutationRepair.ts
// Robust parser and self-healing engine for LLM-generated JSON mutation plans.
// Handles code-fences, trailing commas, unquoted keys, and partial malformed elements.

import { AIMutationPlanSchema, GraphMutationSchema } from "@/schemas/mutations";
import { AIMutationPlan, GraphMutation } from "@/types/mutations";

export interface RepairResult {
  success: boolean;
  plan: AIMutationPlan | null;
  recoveredMutationsCount: number;
  droppedMutationsCount: number;
  warnings: string[];
}

/**
 * Attempts to repair malformed JSON string generated by LLMs.
 */
function sanitizeJsonString(raw: string): string {
  let cleaned = raw.trim();

  // Strip markdown code fences if present (```json ... ``` or ``` ...)
  const fenceRegex = /^```(?:json)?\s*([\s\S]*?)\s*```$/i;
  const matchFence = cleaned.match(fenceRegex);
  if (matchFence && matchFence[1]) {
    cleaned = matchFence[1].trim();
  } else {
    // If there's leading/trailing narrative around the first '{' and last '}'
    const firstBrace = cleaned.indexOf("{");
    const lastBrace = cleaned.lastIndexOf("}");
    if (firstBrace !== -1 && lastBrace !== -1 && lastBrace > firstBrace) {
      cleaned = cleaned.substring(firstBrace, lastBrace + 1);
    }
  }

  // Remove single line comments // ...
  cleaned = cleaned.replace(/\/\/[^"\n\r]*/g, "");

  // Remove trailing commas in objects or arrays: e.g. { "a": 1, } -> { "a": 1 }
  cleaned = cleaned.replace(/,\s*([}\]])/g, "$1");

  return cleaned;
}

/**
 * Parses and repairs an AI mutation plan from raw LLM output text.
 */
export function parseAndRepairMutationPlan(rawOutput: string): RepairResult {
  const warnings: string[] = [];

  if (!rawOutput || !rawOutput.trim()) {
    return {
      success: false,
      plan: null,
      recoveredMutationsCount: 0,
      droppedMutationsCount: 0,
      warnings: ["Empty AI output received"],
    };
  }

  const cleanedJson = sanitizeJsonString(rawOutput);

  let parsedRaw: unknown;
  try {
    parsedRaw = JSON.parse(cleanedJson);
  } catch (err) {
    // If still fails, try closing unclosed braces/brackets
    try {
      let patched = cleanedJson;
      const openBraces = (patched.match(/\{/g) || []).length;
      const closeBraces = (patched.match(/\}/g) || []).length;
      if (openBraces > closeBraces) {
        patched += "}".repeat(openBraces - closeBraces);
      }
      const openBrackets = (patched.match(/\[/g) || []).length;
      const closeBrackets = (patched.match(/\]/g) || []).length;
      if (openBrackets > closeBrackets) {
        patched += "]".repeat(openBrackets - closeBrackets);
      }
      parsedRaw = JSON.parse(patched);
      warnings.push("Auto-closed unbalanced brackets in LLM JSON payload");
    } catch {
      return {
        success: false,
        plan: null,
        recoveredMutationsCount: 0,
        droppedMutationsCount: 0,
        warnings: [`Failed to parse JSON: ${err instanceof Error ? err.message : String(err)}`],
      };
    }
  }

  // Attempt strict validation first
  const strictResult = AIMutationPlanSchema.safeParse(parsedRaw);
  if (strictResult.success) {
    return {
      success: true,
      plan: strictResult.data,
      recoveredMutationsCount: strictResult.data.mutations.length,
      droppedMutationsCount: 0,
      warnings,
    };
  }

  // Fallback: If root is an object, salvage explanation and valid individual mutations
  if (typeof parsedRaw === "object" && parsedRaw !== null) {
    const candidate = parsedRaw as Record<string, unknown>;
    const explanation = typeof candidate.explanation === "string" 
      ? candidate.explanation 
      : "AI proposed architecture updates";

    const rawMutations = Array.isArray(candidate.mutations) ? candidate.mutations : [];
    const validMutations: GraphMutation[] = [];
    let dropped = 0;

    for (const item of rawMutations) {
      const mutResult = GraphMutationSchema.safeParse(item);
      if (mutResult.success) {
        validMutations.push(mutResult.data);
      } else {
        dropped++;
        warnings.push(`Dropped malformed mutation: ${mutResult.error.issues.map((i) => i.message).join(", ")}`);
      }
    }

    if (validMutations.length > 0 || typeof candidate.explanation === "string") {
      return {
        success: true,
        plan: {
          explanation,
          mutations: validMutations,
        },
        recoveredMutationsCount: validMutations.length,
        droppedMutationsCount: dropped,
        warnings,
      };
    }
  }

  return {
    success: false,
    plan: null,
    recoveredMutationsCount: 0,
    droppedMutationsCount: 0,
    warnings: ["Output object does not contain a recoverable mutation plan"],
  };
}
