// Zod runtime schemas for AI mutation validation.
// Mirrors the TypeScript types in src/types/mutations.ts and src/types/semantic.ts.
// Used to validate AI-generated mutation output before it reaches the mutation engine.
//
// These schemas enforce structure only — referential integrity checks
// (e.g. "does the target node exist?") belong in the mutation engine, not here.

import { z } from "zod";

// ─── Semantic Enums ──────────────────────────────────────────────────────────
// Matches NodeType from src/types/semantic.ts

export const NodeTypeSchema = z.enum([
  "service",
  "database",
  "api",
  "queue",
  "cache",
  "gateway",
  "client",
]);

// Matches EdgeRelationship from src/types/semantic.ts

export const EdgeRelationshipSchema = z.enum([
  "connects_to",
  "reads_from",
  "writes_to",
  "publishes_to",
  "subscribes_to",
]);

// ─── Semantic Node ───────────────────────────────────────────────────────────
// Matches SemanticNode from src/types/semantic.ts

export const SemanticNodeSchema = z.object({
  id: z.string(),
  type: NodeTypeSchema,
  name: z.string(),
  technology: z.string().optional(),
  description: z.string().optional(),
  responsibilities: z.array(z.string()).optional(),
  properties: z.record(z.string(), z.string()).optional(),
}).strict();

// ─── Individual Mutation Schemas ─────────────────────────────────────────────
// Each matches its corresponding interface from src/types/mutations.ts

// AddNodeMutation — action: "ADD_NODE", node: SemanticNode
export const AddNodeMutationSchema = z.object({
  action: z.literal("ADD_NODE"),
  node: SemanticNodeSchema,
}).strict();

// RemoveNodeMutation — action: "REMOVE_NODE", nodeId: string
export const RemoveNodeMutationSchema = z.object({
  action: z.literal("REMOVE_NODE"),
  nodeId: z.string(),
}).strict();

// UpdateNodeMutation — action: "UPDATE_NODE", nodeId: string,
// updates: Partial<Omit<SemanticNode, "id">>
const SemanticNodeUpdatesSchema = SemanticNodeSchema.omit({ id: true }).partial();

export const UpdateNodeMutationSchema = z.object({
  action: z.literal("UPDATE_NODE"),
  nodeId: z.string(),
  updates: SemanticNodeUpdatesSchema,
}).strict();

// AddEdgeMutation — action: "ADD_EDGE", edge: Omit<SemanticEdge, "id">
// Edge id is generated by the mutation engine, not by the AI.
const AddEdgePayloadSchema = z.object({
  source: z.string(),
  target: z.string(),
  relationship: EdgeRelationshipSchema,
  label: z.string().optional(),
  protocol: z.string().optional(),
}).strict();

export const AddEdgeMutationSchema = z.object({
  action: z.literal("ADD_EDGE"),
  edge: AddEdgePayloadSchema,
}).strict();

// RemoveEdgeMutation — action: "REMOVE_EDGE", edgeId: string
export const RemoveEdgeMutationSchema = z.object({
  action: z.literal("REMOVE_EDGE"),
  edgeId: z.string(),
}).strict();

// ─── GraphMutation (discriminated union on "action") ─────────────────────────
// Matches GraphMutation from src/types/mutations.ts

export const GraphMutationSchema = z.discriminatedUnion("action", [
  AddNodeMutationSchema,
  RemoveNodeMutationSchema,
  UpdateNodeMutationSchema,
  AddEdgeMutationSchema,
  RemoveEdgeMutationSchema,
]);

// ─── AIMutationPlan ──────────────────────────────────────────────────────────
// Matches AIMutationPlan from src/types/mutations.ts
// This is the top-level schema for validating complete AI output.

export const AIMutationPlanSchema = z.object({
  explanation: z.string(),
  mutations: z.array(GraphMutationSchema),
}).strict();
