// Zod runtime schemas for AI mutation validation.
// Mirrors the TypeScript types in src/types/mutations.ts and src/types/semantic.ts.
// Used to validate AI-generated mutation output before it reaches the mutation engine.

import { z } from "zod";
import { NodeTypeSchema, SemanticNodeSchema } from "./semanticNode";
import { EdgeRelationshipSchema } from "./semanticEdge";

export { NodeTypeSchema, SemanticNodeSchema, EdgeRelationshipSchema };

// ─── Individual Mutation Schemas ─────────────────────────────────────────────

// AddNodeMutation — action: "ADD_NODE", node: SemanticNode
export const AddNodeMutationSchema = z.object({
  action: z.literal("ADD_NODE"),
  node: SemanticNodeSchema,
});

// RemoveNodeMutation — action: "REMOVE_NODE", nodeId: string
export const RemoveNodeMutationSchema = z.object({
  action: z.literal("REMOVE_NODE"),
  nodeId: z.string(),
});

// UpdateNodeMutation — action: "UPDATE_NODE", nodeId: string,
// updates: Partial<Omit<SemanticNode, "id">>
const SemanticNodeUpdatesSchema = SemanticNodeSchema.omit({ id: true }).partial();

export const UpdateNodeMutationSchema = z.object({
  action: z.literal("UPDATE_NODE"),
  nodeId: z.string(),
  updates: SemanticNodeUpdatesSchema,
});

// AddEdgeMutation — action: "ADD_EDGE", edge: Omit<SemanticEdge, "id">
// Edge id is generated by the mutation engine, not by the AI.
const AddEdgePayloadSchema = z.object({
  source: z.string(),
  target: z.string(),
  relationship: EdgeRelationshipSchema,
  label: z.string().optional(),
  protocol: z.string().optional(),
});

export const AddEdgeMutationSchema = z.object({
  action: z.literal("ADD_EDGE"),
  edge: AddEdgePayloadSchema,
});

// RemoveEdgeMutation — action: "REMOVE_EDGE", edgeId: string
export const RemoveEdgeMutationSchema = z.object({
  action: z.literal("REMOVE_EDGE"),
  edgeId: z.string(),
});

// ─── GraphMutation (discriminated union on "action") ─────────────────────────
export const GraphMutationSchema = z.discriminatedUnion("action", [
  AddNodeMutationSchema,
  RemoveNodeMutationSchema,
  UpdateNodeMutationSchema,
  AddEdgeMutationSchema,
  RemoveEdgeMutationSchema,
]);

// ─── AIMutationPlan ──────────────────────────────────────────────────────────
export const AIMutationPlanSchema = z.object({
  explanation: z.string(),
  mutations: z.array(GraphMutationSchema),
});
