// POST /api/ai/artifacts — Artifact generation endpoint.
// Receives the graph + desired artifact type. Returns the generated artifact content
// along with metadata (filename, language) as a custom header for the client.
//
// From SYSTEM_DESIGN §8.1:
//   1. Parse and validate request body (Zod)
//   2. Select artifact-specific prompt template
//   3. Inject serialized graph as context
//   4. Call LLM via Vercel AI SDK
//   5. Stream artifact content back to client

import { openai } from "@ai-sdk/openai";
import { streamText } from "ai";
import { getArtifactPrompt } from "@/lib/prompts";
import { ArtifactRequestSchema, ARTIFACT_METADATA } from "@/schemas/artifacts";
import { sanitizeGraph } from "@/lib/sanitizer";
import { validateGraphForArtifacts } from "@/engine/artifactValidator";

// Allow streaming responses up to 60 seconds (artifact generation can be longer)
export const maxDuration = 60;

export async function POST(req: Request) {
  try {
    const rawBody = await req.json();

    // ── Step 1: Zod validation ──────────────────────────────────────────────
    const parsed = ArtifactRequestSchema.safeParse(rawBody);
    if (!parsed.success) {
      return Response.json(
        {
          error: "Validation error",
          code: "VALIDATION_ERROR" as const,
          details: parsed.error.issues
            .map((i) => `${i.path.join(".")}: ${i.message}`)
            .join("; "),
        },
        { status: 400 }
      );
    }

    const { graph, artifactType } = parsed.data;

    // ── Step 2: Sanitize graph ──────────────────────────────────────────────
    const { sanitizedGraph, redactionCount } = sanitizeGraph(graph);

    // ── Step 3: Deterministic Pre-Validation ─────────────────────────────────
    const validation = validateGraphForArtifacts(sanitizedGraph, artifactType);
    if (!validation.valid) {
      return Response.json(
        {
          error: "Graph architecture contains critical errors preventing artifact generation",
          code: "ARTIFACT_PREVALIDATION_FAILED",
          details: validation.errors.join("; "),
        },
        { status: 422 }
      );
    }

    // ── Step 4: Get artifact-specific prompt and metadata ───────────────────
    const systemPrompt = getArtifactPrompt(artifactType);
    const metadata = ARTIFACT_METADATA[artifactType];

    const promptContext = `Please generate the artifact based on this architecture graph:\n\n${JSON.stringify(sanitizedGraph, null, 2)}${
      artifactType === "docker-compose"
        ? `\n\nVerified Host Port Allocations:\n${JSON.stringify(validation.portMap, null, 2)}`
        : ""
    }`;

    // ── Step 5: Call the LLM or Deterministic Compiler ─────────────────────
    if (!process.env.OPENAI_API_KEY) {
      let content = "";

      if (artifactType === "docker-compose") {
        content = `# Generated by Flowboard Architecture Compiler\nversion: '3.8'\n\nservices:\n`;
        for (const node of sanitizedGraph.nodes) {
          const serviceName = node.name.toLowerCase().replace(/[^a-z0-9]/g, "-");
          const tech = (node.technology || "").toLowerCase();
          let image = "alpine:latest";
          let defaultPort = 8080;

          if (tech.includes("postgres")) {
            image = "postgres:16-alpine";
            defaultPort = 5432;
          } else if (tech.includes("redis")) {
            image = "redis:7-alpine";
            defaultPort = 6379;
          } else if (tech.includes("kafka")) {
            image = "confluentinc/cp-kafka:latest";
            defaultPort = 9092;
          } else if (tech.includes("mongo")) {
            image = "mongo:6-jammy";
            defaultPort = 27017;
          } else if (node.type === "gateway") {
            image = "kong:latest";
            defaultPort = 8000;
          } else if (node.type === "service") {
            image = `node:20-alpine`;
            defaultPort = 3000;
          }

          content += `  ${serviceName}:\n`;
          content += `    image: ${image}\n`;
          content += `    container_name: flowboard-${serviceName}\n`;
          content += `    ports:\n      - "${defaultPort}:${defaultPort}"\n`;
          content += `    environment:\n      - NODE_ENV=production\n      - SERVICE_NAME=${node.name}\n`;

          const dependencies = sanitizedGraph.edges
            .filter((e) => e.source === node.id)
            .map((e) => sanitizedGraph.nodes.find((n) => n.id === e.target))
            .filter(Boolean);

          if (dependencies.length > 0) {
            content += `    depends_on:\n`;
            for (const dep of dependencies) {
              content += `      - ${dep!.name.toLowerCase().replace(/[^a-z0-9]/g, "-")}\n`;
            }
          }
          content += `    restart: unless-stopped\n\n`;
        }
      } else if (artifactType === "architecture-readme") {
        content = `# System Architecture: Comprehensive Specification\n\n`;
        content += `> Automatically compiled from Flowboard semantic architecture graph.\n\n`;
        content += `## System Topology\n\n- **Total Components:** ${sanitizedGraph.nodes.length}\n`;
        content += `- **Total Connections:** ${sanitizedGraph.edges.length}\n\n`;
        content += `## Component Directory\n\n`;
        for (const node of sanitizedGraph.nodes) {
          content += `### ${node.name} (\`${node.type.toUpperCase()}\`)\n`;
          content += `- **Technology:** ${node.technology || "Unspecified"}\n`;
          content += `- **Description:** ${node.description || "Core system component"}\n`;
          if (node.responsibilities && node.responsibilities.length > 0) {
            content += `- **Key Responsibilities:**\n`;
            for (const r of node.responsibilities) {
              content += `  - ${r}\n`;
            }
          }
          content += `\n`;
        }
        content += `## Communication Flows & Protocols\n\n`;
        for (const edge of sanitizedGraph.edges) {
          const src = sanitizedGraph.nodes.find((n) => n.id === edge.source)?.name || edge.source;
          const tgt = sanitizedGraph.nodes.find((n) => n.id === edge.target)?.name || edge.target;
          content += `- **${src}** ➔ **${tgt}** via \`${edge.relationship}\`${edge.protocol ? ` (${edge.protocol})` : ""}${edge.label ? `: "${edge.label}"` : ""}\n`;
        }
      } else if (artifactType === "api-contracts") {
        content = `// TypeScript API Contracts & Boundary Types\n// Generated by Flowboard\n\n`;
        for (const node of sanitizedGraph.nodes) {
          const typeName = node.name.replace(/[^a-zA-Z0-9]/g, "");
          content += `export interface ${typeName}DTO {\n`;
          content += `  id: string;\n`;
          content += `  timestamp: number;\n`;
          if (node.responsibilities) {
            for (const r of node.responsibilities) {
              const fieldName = r.toLowerCase().replace(/[^a-z0-9]/g, "_");
              content += `  ${fieldName}?: boolean | string;\n`;
            }
          }
          content += `}\n\n`;
        }
      } else {
        content = `# Environment Configuration Template\n# Generated by Flowboard\n\n`;
        for (const node of sanitizedGraph.nodes) {
          const prefix = node.name.toUpperCase().replace(/[^A-Z0-9]/g, "_");
          content += `# ── ${node.name} (${node.technology || node.type}) ──\n`;
          content += `${prefix}_HOST=localhost\n`;
          content += `${prefix}_PORT=8080\n`;
          content += `${prefix}_API_KEY=your_${prefix.toLowerCase()}_key_here\n\n`;
        }
      }

      const response = new Response(content, {
        headers: {
          "Content-Type": "text/plain; charset=utf-8",
          "X-Artifact-Filename": metadata.filename,
          "X-Artifact-Language": metadata.language,
          "X-Artifact-Type": artifactType,
          "X-Flowboard-Mode": "compiler",
        },
      });
      return response;
    }

    const result = streamText({
      model: openai("gpt-4o"),
      system: systemPrompt,
      prompt: promptContext,
      temperature: 0.1, // Very low for precise code/config generation
    });

    // ── Step 5: Stream with metadata headers ────────────────────────────────
    const response = result.toTextStreamResponse();

    // Attach artifact metadata as custom headers so the client knows
    // what filename/language to use for preview and download
    response.headers.set("X-Artifact-Filename", metadata.filename);
    response.headers.set("X-Artifact-Language", metadata.language);
    response.headers.set("X-Artifact-Type", artifactType);
    response.headers.set("X-Flowboard-Redactions", String(redactionCount));

    return response;
  } catch (error) {
    console.error("AI Artifact API Error:", error);

    if (error instanceof SyntaxError) {
      return Response.json(
        { error: "Invalid JSON in request body", code: "VALIDATION_ERROR" as const },
        { status: 400 }
      );
    }

    return Response.json(
      { error: "Internal server error", code: "INTERNAL_ERROR" as const },
      { status: 500 }
    );
  }
}
